# 字典表, 注意，注意，注意：字典表的key不要随意改，会影响用到此字段的地方
# 字典表, 注意，注意，注意： 可以必须是字符串，要加引号
# 字典表, 注意，注意，注意： 可以必须是字符串，要加引号
# 字典表, 注意，注意，注意： 可以必须是字符串，要加引号
dict-mapping:
  "field_group_type": "分组字典"
  "server_type": "调图类型字典"
  "x_type": "红线类型字典"
  "b_landuse_type": "用地性质字典"
  "tk_type": "图廓类型字典"

field-group-type: # 分组
  "0": "基础信息"
  "1": "审批信息"
  "2": "扩展属性"
  "3": "其它属性"

server-type: # 调图类型
  "1": "数据库空间数据调图"
  "2": "dwg调图"
  "3": "tif调图"
  "4": "arcgis服务调图"

x-type: # 红线类型
  "100001": "正式红线"
  "100002": "选址红线"
  "100003": "临时红线"
  "100004": "意向红线"
  "100005": "道路河道红线"
  "100006": "退地红线"
  "100007": "土地挂牌"
  "100008": "道路红线（划拨）"
  "100009": "道路红线（改扩建）"
  "100010": "道路红线（选址）"

b-landuse-type: # 用地性质
  "1140100": "居住用地"
  "1140110": "公共管理与公共服务用地"
  "1140120": "商业服务业设施用地"
  "1140130": "工业用地"
  "1140140": "物流仓储用地"
  "1140150": "道路与交通设施用地"
  "1140160": "公用设施用地"
  "1140170": "绿地与广场用地"
  "1140180": "其它"
  "1140181": "供电用地"
  "1140182": "文化设施用地"
  "1140183": "教育科研用地"
  "1140184": "其他交通设施用地"
  "1140185": "区域公共设施用地"
  "1140186": "农林用地"

db-fields-type: # 数据库字段类型
  "VARCHAR": "VARCHAR (字符)"
  "NUMBER": "NUMBER (带小数位数字)"
  "INTEGER": "INTEGER (整数)"
  "DATE": "DATE (日期)"
  "DATETIME": "DATETIME (日期时间)"


tk-type: # 图廓类型
  "意向红线图": "意向红线图.dwg"
  "选址红线图": "选址红线图.dwg"
  "用地红线图(A3)": "用地红线图（A3）.dwg"
  "用地红线图(道路)(A3)": "用地红线图(道路)(A3).dwg"
  "建筑红线图": "建筑红线图.dwg"
  "用地红线图-新(A3)": "用地红线图-新(A3).dwg"
  "意向红线图-新(A3)": "意向红线图-新(A3).dwg"
  "临时红线图-新(A3)": "临时红线图-新(A3).dwg"
  "选址红线图-新(A3)": "选址红线图-新(A3).dwg"
  
msfs-type: # 图廓类型
  "1": "直埋"
  "2": "套管"
  "3": "管块"
  "4": "方沟"
  "5": "架空"
  "6": "拱沟"
  "7": "排管"
  "8": "人防"
  "9": "隧道"
  "10": "其他"
  "11": "组合"
  "12": "地上"
  "13": "地下"

field-nullable:   # 是否可为空
  "1": "可为空"
  "0": "不可为空"